### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by tekkeitserktok** [M8s-dev/android_device_htc_m8qlul#1]
Hey,

I own a M8s and I'd like to help you but I know nothing about building a custom rom.
Do you have any tutorial in order to build your repo and a roadmap to follow ?

Thanks !

**Comment by voidzero** [comment]
Oh hi there, sorry I missed your issue request.

Well, this ROM doesn't work yet, it's a work in progress. There are build tutorials on wiki.cyanogenmod.org. Regarding a roadmap... there is none. Just, compile, test some stuff, make changes, compile again, test some more, make some changes.....

**Comment by tekkeitserktok** [comment]
Ok thanks for the answer !
