### ISSUE TITLE
Audio disables after 30 seconds

### ISSUE THREAD

**Issue by voidzero** [M8s-dev/android_device_htc_m8qlul#6]
:unamused:

**Comment by PatrikKT** [comment]
Cherrypick these to fix it:
https://github.com/HTC-MSM8916/android_device_htc_a31ul/commit/a3a6b516add861ad92d5e4873d0aceb13b45f26f
https://github.com/HTC-MSM8916/android_device_htc_msm8916-common/commit/0e0a9cb5b43cb23d3b6e02041b711bab85a7ef4f

**Comment by voidzero** [comment]
Well, it's a workaround because it disables offloading, but we'll do it like this until I've found a better alternative. Thanks.
